#---------------------------------------------------------------
# Theme version infromation
#---------------------------------------------------------------
version: 1.0

#---------------------------------------------------------------
# Build setting
#---------------------------------------------------------------
gems: [jekyll-paginate]
# Config sass build output by sass_dir
# Config sass output is compressed or not
#
sass:
    sass_dir: /assets/stylesheet
    style: :compressed


#---------------------------------------------------------------
# Site infromation setting
#---------------------------------------------------------------

# Site
## You can create a locale setting at _locales and name *.yml
title: "Tony的博客"
description: ""
keywords: "Tony"
locale: "zh_CN"

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and baseurl as '/child/'
url: "http://lituoweb.cn"
baseurl: ""
permalink: /:year/:month/:day/:title


# Pagination
## Set per_page to 0 to disable pagination
paginate: 8
paginate_path: "/page:num/"


# Writing
markdown: "redcarpet"
# highlighter: "pygments"
highlighter: 'pygments'
#kramdown:
#  input:  GFM
#  enable_coderay: true
#  coderay:
#    coderay_line_numbers:  nil

# RSS
rss:
  path: "/feed.xml"
  icon: "rss"

# 分类模板中英转换，为了解决不支持中文路径的问题
# 每个增加的分类都必须在此增加英文名称
convert:
  工具: "tools"
  操作系统: "os"

#---------------------------------------------------------------
# Authour infromation setting
#---------------------------------------------------------------

# Author
author:
  name: "btonylee"
  avatar: "assets/images/logo.png"
  motto: "怕什么真理无穷 进一寸有一寸的欢喜"

# Socials
## If you want the social show,place sure the social no comment
## The socials icon base font-awesome,you can learn more on http://fontawesome.io/icons/
socials:
    # - name: "weibo"
    #   url: "http://www.weibo.com/usename/"
    #   icon: "weibo"
    - name: "github"
      url: "https://github.com/btonylee"
      icon: "github"
    # - name: "facebook"
    #   url: "https://www.facebook.com/usename"
    #   icon: "facebook"




#---------------------------------------------------------------
# Site comment setting
#---------------------------------------------------------------

comment:
  enable: true

# duoshuo
duoshuo:
  enable: true
  short_name: "btonylee"

# disqus
disqus:
  enable: false
  short_name: "your disqus short_name"

#---------------------------------------------------------------
# Site share setting
#---------------------------------------------------------------
duoshuo_share:
    enable: true

#---------------------------------------------------------------
# Site analysis setting
#---------------------------------------------------------------
# Baidu analysis
baidu_analysis:
  enable: false
  token: "37a3e759e3a05b9fcf4cecbf42e32c4c"

# Google analysis
google_analysus:
  enable: false
  token: "your google analysis token"
